sudo: required

language: ruby

cache:
  directories:
  - docker

services:
  - docker

before_install:
  - rake docker:build

script:
  - rake docker:test:all

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ]); then rake docker:publish; fi
