sudo: required

language: ruby

cache:
  directories:
  - docker
  - vendor/bundle

services:
  - docker

before_install:
  - gem install -f docker-api

script:
  # - ruby _scripts/travis-docker-test.rb
  - bundle exec rake docker:build
  - bundle exec rspec spec/soe

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ]); then bundle exec rake docker:publish; fi
