sudo: required

language: ruby

cache:
  directories:
  - docker
  - vendor/bundle

services:
  - docker

before_install:
  - ruby _scripts/travis-docker-test.rb

script:
  - bundle exec rake docker:build
  - bundle exec rspec spec/soe/php55_spec.rb

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ]); then bundle exec rake docker:publish; fi
