sudo: required

language: ruby

cache:
  directories:
  - docker

services:
  - docker

script:
  - bundle exec rake docker:build
  - bundle exec rake docker:test:all

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ]); then rake docker:publish; fi
