sudo: required

language: ruby

cache:
  directories:
  - docker

services:
  - docker

before_install:
  - docker info
  - invalid_cmd

script:
  - bundle exec rake docker:build
  - bundle exec rspec spec/soe

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ]); then bundle exec rake docker:publish; fi
