FROM docker:17.06-dind
MAINTAINER Chin Godawita <chin.godawita@me.com>

# Install Ruby
RUN apk update && apk upgrade
RUN apk add git curl wget bash ruby ruby-dev ruby-bundler
RUN rm -rf /var/cache/apk/*

RUN mkdir /code
WORKDIR /code

# Setup dependencies.
COPY Gemfile /code/
COPY Gemfile.lock /code/
RUN bundle install --jobs 20 --retry 5
