# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install

      - run:
          name: build containers
          command: |
            bundle exec rake docker:ci_build

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/ubuntu_*_spec.rb" | circleci tests split --split-by=timings)"

            echo "BEFORE:"
            echo $TEST_FILES
            echo ":AFTER YO"

            bundle exec rspec --format progress \
                --format RspecJunitFormatter \
                --out /tmp/test-results/rspec.xml \
                --format progress \
                -- \
                $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
